### ISSUE TITLE
Custom types not working

### ISSUE THREAD

**Issue by insalab** [jeromegn/dry-data-rails#2]
Hi! When I add this gem into the project it somehow redefines `Types` module which is defined like this in my project

```
module Types
  include Dry::Types.module
end
```

When I try to use types in my classes 

```
attribute :phone, Types::String
```

I get an error `uninitialized constant Types::String`.
If I remove this gem and leave only `dry-types` in `Gemfile` the error is gone.

The code of this gem is really simple but I can't understand why it behaves this way.

**Comment by sumskyi** [comment]
The same for me, 

``` ruby
module Types
  include Dry::Types.module

  ZeroBox = Coercible::Int.default(0)
end
```

NameError (uninitialized constant Types::Coercible)

after removing `gem 'dry-types-rails'` from `Gemfile` it works again

```
-> % cat Gemfile.lock | grep dry-
    dry-configurable (0.1.4)
    dry-container (0.3.1)
      dry-configurable (~> 0.1, >= 0.1.3)
    dry-equalizer (0.2.0)
    dry-logic (0.2.1)
      dry-container (~> 0.2, >= 0.2.6)
      dry-equalizer (~> 0.2)
    dry-types (0.6.0)
      dry-configurable (~> 0.1)
      dry-container (~> 0.2)
      dry-equalizer (~> 0.2)
      dry-logic (~> 0.2, >= 0.2.0)
    dry-types-rails (0.2.0)
      dry-types
    dry-validation (0.7.1)
      dry-configurable (~> 0.1, >= 0.1.3)
      dry-container (~> 0.2, >= 0.2.8)
      dry-equalizer (~> 0.2)
      dry-logic (~> 0.2, >= 0.2.1)
      dry-types (~> 0.6, >= 0.6.0)
  dry-types
  dry-types-rails
  dry-validation
```

**Comment by jeromegn** [comment]
I was able to reproduce in the spec. Investigating.

**Comment by jeromegn** [comment]
I stopped using Dry::Types, it didn't pan out to be a viable alternative for my project.

I discussed in the [Dry::Types gitter chat](https://gitter.im/dry-rb/chat), the conversation about it starts here: https://gitter.im/dry-rb/chat?at=56fa7e2276b6f9de194c1db5

Basically, it would require quite a bit of doing to make sure this works. Sadly, since I won't be using Dry::Types anymore (inappropriate for my project), I won't be putting more time into this gem.

If anybody wants to do the work and get the namespace on rubygems, I'll be happy to give it away!

**Comment by pnomolos** [comment]
@jeromegn I've been looking into this.  The problem is that `to_prepare` actually fires before 

``` ruby
module Types
  include Dry::Types.module
end
```

is run, and removes all the built-in types (I'm still trying to figure out why unsetting `:@container` is doing that, though).

If you add `load "dry/types/core.rb"` after the call to remove the instance variable it _works_, but you get lots of fun warnings about overriding constants ;)

**Comment by andypearson** [comment]
@jeromegn I've ended up at this repo whilst considering using `dry-types` in a Rails project. Would you be able to explain why it wasn't viable and what you are doing/using instead?

**Comment by pnomolos** [comment]
@andypearson While you're certainly free to use something else, I _should_ point out that we're currently using `dry-types-rails` for a large project and it seems to be working fine, if you still were interested in using `dry-types` :)

**Comment by andypearson** [comment]
@pnomolos Thanks for the heads-up :)

Did you have any luck finding a fix for this issue that didn't result in a bunch of warnings? I'm imagining I'll need custom types at some point...

**Comment by pnomolos** [comment]
Warnings about constants being redefined? Just make sure to use
'require_dependency' so it plays nice with Rails' autoloader. Or were you
getting other warnings?
